### ISSUE TITLE
Tests not commited

### ISSUE THREAD

**Issue by gnugat** [DavertMik/SymfonyCodeceptionApp#1]
Hi! I can't seem to find the tests, the only thing I found was the PHPStorm configuration which was modified.
It makes me sad because I don't use PHPStorm...
Did I miss something?

**Comment by DavertMik** [comment]
I was in process writing those tests )
Now they are in `tests` directory, right now there are functional tests, as they are most sensitive to framework implementation

**Comment by gnugat** [comment]
Great, thanks for the update!
